export const SLINGSHOT_RESTITUTION = 50

export const SLINGSHOT_TREMBLE_DURATION = 0.3
export const SLINGSHOT_TREMBLE_AMP = 0.05
export const SLINGSHOT_TREMBLE_FREQ = 80

export const SLINGSHOT_STUCK_FRAMES = 30
export const SLINGSHOT_STUCK_VELOCITY = 0.5
export const SLINGSHOT_UNSTICK_IMPULSE = 5
