import type { BackendConfigKey } from "./backendConfigTypes"

export type BackendConfigCategory =
  | "Core"
  | "Scoring"
  | "Multiball"
  | "Timer bonus"
  | "Tilt"
  | "Boss HP"
  | "Boss difficulty"
  | "Combo system"
  | "Combo bonuses"
  | "Character ultimates"
  | "Streak"
  | "Rail"
  | "PVE timing"

export interface BackendConfigCategoryDefinition {
  label: BackendConfigCategory
  collapsed: boolean
}

export type BackendConfigNumberKind = "float" | "integer"

export interface BackendConfigField {
  key: BackendConfigKey
  label: string
  category: BackendConfigCategory
  kind: BackendConfigNumberKind
  min?: number
  max?: number
  step: number
}

export const BACKEND_CONFIG_CATEGORIES = [
  { label: "Core", collapsed: false },
  { label: "Scoring", collapsed: true },
  { label: "Multiball", collapsed: true },
  { label: "Timer bonus", collapsed: true },
  { label: "Tilt", collapsed: true },
  { label: "Boss HP", collapsed: true },
  { label: "Boss difficulty", collapsed: true },
  { label: "Combo system", collapsed: true },
  { label: "Combo bonuses", collapsed: true },
  { label: "Character ultimates", collapsed: true },
  { label: "Streak", collapsed: true },
  { label: "Rail", collapsed: true },
  { label: "PVE timing", collapsed: true },
] as const satisfies readonly BackendConfigCategoryDefinition[]

export const BACKEND_CONFIG_FIELDS = [
  {
    key: "default_lives",
    label: "Default lives",
    category: "Core",
    kind: "integer",
    min: 1,
    max: 9,
    step: 1,
  },
  {
    key: "ultime_charge_ratio",
    label: "Ultimate charge ratio",
    category: "Core",
    kind: "integer",
    min: 1,
    max: 500,
    step: 1,
  },
  {
    key: "ball_saver_score",
    label: "Ball saver score",
    category: "Scoring",
    kind: "integer",
    min: 0,
    max: 10000,
    step: 50,
  },
  {
    key: "bumper_score",
    label: "Bumper score",
    category: "Scoring",
    kind: "integer",
    min: 0,
    max: 10000,
    step: 50,
  },
  {
    key: "bumper_triangle_score",
    label: "Triangle bumper score",
    category: "Scoring",
    kind: "integer",
    min: 0,
    max: 10000,
    step: 50,
  },
  {
    key: "portal_score",
    label: "Portal score",
    category: "Scoring",
    kind: "integer",
    min: 0,
    max: 10000,
    step: 50,
  },
  {
    key: "multiball_ring_threshold",
    label: "Ring threshold",
    category: "Multiball",
    kind: "integer",
    min: 1,
    max: 100,
    step: 1,
  },
  {
    key: "multiball_score",
    label: "Score",
    category: "Multiball",
    kind: "integer",
    min: 0,
    max: 50000,
    step: 50,
  },
  {
    key: "timer_bonus_seconds",
    label: "Trigger seconds",
    category: "Timer bonus",
    kind: "integer",
    min: 1,
    max: 600,
    step: 1,
  },
  {
    key: "timer_bonus_score",
    label: "Score",
    category: "Timer bonus",
    kind: "integer",
    min: 0,
    max: 50000,
    step: 50,
  },
  {
    key: "timer_bonus_multiplier",
    label: "Multiplier",
    category: "Timer bonus",
    kind: "float",
    min: 0,
    max: 10,
    step: 0.05,
  },
  {
    key: "tilt_penalty_1",
    label: "First penalty",
    category: "Tilt",
    kind: "integer",
    min: -100000,
    max: 0,
    step: 100,
  },
  {
    key: "tilt_penalty_2",
    label: "Second penalty",
    category: "Tilt",
    kind: "integer",
    min: -100000,
    max: 0,
    step: 100,
  },
  {
    key: "boss_0_hp",
    label: "Boss 0 HP",
    category: "Boss HP",
    kind: "integer",
    min: 1,
    max: 2000000,
    step: 1000,
  },
  {
    key: "boss_1_hp",
    label: "Boss 1 HP",
    category: "Boss HP",
    kind: "integer",
    min: 1,
    max: 2000000,
    step: 1000,
  },
  {
    key: "boss_2_hp",
    label: "Boss 2 HP",
    category: "Boss HP",
    kind: "integer",
    min: 1,
    max: 3000000,
    step: 1000,
  },
  {
    key: "boss_0_difficulty_scale",
    label: "Boss 0 scale",
    category: "Boss difficulty",
    kind: "float",
    min: 0,
    max: 10,
    step: 0.05,
  },
  {
    key: "boss_1_difficulty_scale",
    label: "Boss 1 scale",
    category: "Boss difficulty",
    kind: "float",
    min: 0,
    max: 10,
    step: 0.05,
  },
  {
    key: "boss_2_difficulty_scale",
    label: "Boss 2 scale",
    category: "Boss difficulty",
    kind: "float",
    min: 0,
    max: 10,
    step: 0.05,
  },
  {
    key: "endless_base_difficulty_scale",
    label: "Endless base scale",
    category: "Boss difficulty",
    kind: "float",
    min: 0,
    max: 10,
    step: 0.05,
  },
  {
    key: "endless_level_scale_exponent",
    label: "Endless exponent",
    category: "Boss difficulty",
    kind: "float",
    min: 0,
    max: 5,
    step: 0.05,
  },
  {
    key: "combo_buffer_max",
    label: "Buffer max",
    category: "Combo system",
    kind: "integer",
    min: 1,
    max: 64,
    step: 1,
  },
  {
    key: "combo_detection_window_ms",
    label: "Detection window ms",
    category: "Combo system",
    kind: "integer",
    min: 100,
    max: 10000,
    step: 50,
  },
  {
    key: "combo_penalty_repeat",
    label: "Penalty repeat",
    category: "Combo system",
    kind: "integer",
    min: 1,
    max: 32,
    step: 1,
  },
  {
    key: "combo_penalty_pts",
    label: "Penalty points",
    category: "Combo system",
    kind: "integer",
    min: -100000,
    max: 100000,
    step: 100,
  },
  {
    key: "combo_2_bonus",
    label: "Combo 2 bonus",
    category: "Combo bonuses",
    kind: "integer",
    min: 0,
    max: 100000,
    step: 50,
  },
  {
    key: "combo_3_bonus",
    label: "Combo 3 bonus",
    category: "Combo bonuses",
    kind: "integer",
    min: 0,
    max: 100000,
    step: 50,
  },
  {
    key: "combo_4_bonus",
    label: "Combo 4 bonus",
    category: "Combo bonuses",
    kind: "integer",
    min: 0,
    max: 100000,
    step: 50,
  },
  {
    key: "combo_5_bonus",
    label: "Combo 5 bonus",
    category: "Combo bonuses",
    kind: "integer",
    min: 0,
    max: 100000,
    step: 50,
  },
  {
    key: "combo_6_bonus",
    label: "Combo 6 bonus",
    category: "Combo bonuses",
    kind: "integer",
    min: 0,
    max: 100000,
    step: 50,
  },
  {
    key: "combo_7_bonus",
    label: "Combo 7 bonus",
    category: "Combo bonuses",
    kind: "integer",
    min: 0,
    max: 100000,
    step: 50,
  },
  {
    key: "combo_8_bonus",
    label: "Combo 8 bonus",
    category: "Combo bonuses",
    kind: "integer",
    min: 0,
    max: 100000,
    step: 50,
  },
  {
    key: "combo_9_bonus",
    label: "Combo 9 bonus",
    category: "Combo bonuses",
    kind: "integer",
    min: 0,
    max: 100000,
    step: 50,
  },
  {
    key: "combo_10_bonus",
    label: "Combo 10 bonus",
    category: "Combo bonuses",
    kind: "integer",
    min: 0,
    max: 100000,
    step: 50,
  },
  {
    key: "combo_11_bonus",
    label: "Combo 11 bonus",
    category: "Combo bonuses",
    kind: "integer",
    min: 0,
    max: 100000,
    step: 50,
  },
  {
    key: "combo_14_bonus",
    label: "Combo 14 bonus",
    category: "Combo bonuses",
    kind: "integer",
    min: 0,
    max: 100000,
    step: 50,
  },
  {
    key: "combo_15_bonus",
    label: "Combo 15 bonus",
    category: "Combo bonuses",
    kind: "integer",
    min: 0,
    max: 100000,
    step: 50,
  },
  {
    key: "combo_16_bonus",
    label: "Combo 16 bonus",
    category: "Combo bonuses",
    kind: "integer",
    min: 0,
    max: 100000,
    step: 50,
  },
  {
    key: "enforcer_charge_max",
    label: "Enforcer charge max",
    category: "Character ultimates",
    kind: "integer",
    min: 1,
    max: 500,
    step: 1,
  },
  {
    key: "enforcer_weight_bumper",
    label: "Enforcer bumper weight",
    category: "Character ultimates",
    kind: "float",
    min: 0,
    max: 10,
    step: 0.05,
  },
  {
    key: "enforcer_weight_rail",
    label: "Enforcer rail weight",
    category: "Character ultimates",
    kind: "float",
    min: 0,
    max: 10,
    step: 0.05,
  },
  {
    key: "enforcer_weight_combo",
    label: "Enforcer combo weight",
    category: "Character ultimates",
    kind: "float",
    min: 0,
    max: 10,
    step: 0.05,
  },
  {
    key: "enforcer_weight_other",
    label: "Enforcer other weight",
    category: "Character ultimates",
    kind: "float",
    min: 0,
    max: 10,
    step: 0.05,
  },
  {
    key: "viper_charge_max",
    label: "Viper charge max",
    category: "Character ultimates",
    kind: "integer",
    min: 1,
    max: 500,
    step: 1,
  },
  {
    key: "viper_ulti_duration_ms",
    label: "Viper duration ms",
    category: "Character ultimates",
    kind: "integer",
    min: 100,
    max: 60000,
    step: 100,
  },
  {
    key: "viper_rampage_multiplier",
    label: "Viper multiplier",
    category: "Character ultimates",
    kind: "float",
    min: 0,
    max: 20,
    step: 0.05,
  },
  {
    key: "ghost_charge_max",
    label: "Ghost charge max",
    category: "Character ultimates",
    kind: "integer",
    min: 1,
    max: 500,
    step: 1,
  },
  {
    key: "oracle_charge_max",
    label: "Oracle charge max",
    category: "Character ultimates",
    kind: "integer",
    min: 1,
    max: 500,
    step: 1,
  },
  {
    key: "oracle_ulti_duration_ms",
    label: "Oracle duration ms",
    category: "Character ultimates",
    kind: "integer",
    min: 100,
    max: 60000,
    step: 100,
  },
  {
    key: "oracle_slow_factor",
    label: "Oracle slow factor",
    category: "Character ultimates",
    kind: "float",
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    key: "oracle_time_rate",
    label: "Oracle time rate",
    category: "Character ultimates",
    kind: "float",
    min: 0,
    max: 10,
    step: 0.05,
  },
  {
    key: "oracle_activation_min_ratio",
    label: "Oracle activation min ratio",
    category: "Character ultimates",
    kind: "float",
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    key: "streak_window_ms",
    label: "Window ms",
    category: "Streak",
    kind: "integer",
    min: 100,
    max: 10000,
    step: 50,
  },
  {
    key: "streak_tier_1_count",
    label: "Tier 1 count",
    category: "Streak",
    kind: "integer",
    min: 1,
    max: 100,
    step: 1,
  },
  {
    key: "streak_tier_2_count",
    label: "Tier 2 count",
    category: "Streak",
    kind: "integer",
    min: 1,
    max: 100,
    step: 1,
  },
  {
    key: "streak_tier_3_count",
    label: "Tier 3 count",
    category: "Streak",
    kind: "integer",
    min: 1,
    max: 100,
    step: 1,
  },
  {
    key: "streak_tier_1_multiplier",
    label: "Tier 1 multiplier",
    category: "Streak",
    kind: "float",
    min: 0,
    max: 20,
    step: 0.05,
  },
  {
    key: "streak_tier_2_multiplier",
    label: "Tier 2 multiplier",
    category: "Streak",
    kind: "float",
    min: 0,
    max: 20,
    step: 0.05,
  },
  {
    key: "streak_tier_3_multiplier",
    label: "Tier 3 multiplier",
    category: "Streak",
    kind: "float",
    min: 0,
    max: 20,
    step: 0.05,
  },
  {
    key: "rail_tick_interval_ms",
    label: "Tick interval ms",
    category: "Rail",
    kind: "integer",
    min: 10,
    max: 5000,
    step: 10,
  },
  {
    key: "rail_max_session_ms",
    label: "Max session ms",
    category: "Rail",
    kind: "integer",
    min: 100,
    max: 120000,
    step: 100,
  },
  {
    key: "rail_base_score",
    label: "Base score",
    category: "Rail",
    kind: "integer",
    min: 0,
    max: 1000,
    step: 1,
  },
  {
    key: "rail_max_fib_step",
    label: "Max fib step",
    category: "Rail",
    kind: "integer",
    min: 0,
    max: 20,
    step: 1,
  },
  {
    key: "boss_death_anim_ms",
    label: "Boss death anim ms",
    category: "PVE timing",
    kind: "integer",
    min: 0,
    max: 60000,
    step: 100,
  },
  {
    key: "boss_score_threshold",
    label: "Boss score threshold",
    category: "PVE timing",
    kind: "integer",
    min: 0,
    max: 1000000,
    step: 500,
  },
  {
    key: "pve_tick_interval_ms",
    label: "PVE tick interval ms",
    category: "PVE timing",
    kind: "integer",
    min: 10,
    max: 5000,
    step: 10,
  },
] as const satisfies readonly BackendConfigField[]

const assertNoMissingBackendConfigKeys = (
  _keys: Record<Exclude<BackendConfigKey, (typeof BACKEND_CONFIG_FIELDS)[number]["key"]>, never>,
): true => true

assertNoMissingBackendConfigKeys({})

export const BACKEND_CONFIG_KEYS = BACKEND_CONFIG_FIELDS.map((field) => field.key)
